# _config.yml (Production)
title: Global Pulse Report
description: Your site description
url: "https://hoakam.github.io"
baseurl: "/globalpulsereport" # Must match repository name
permalink: /:year/:month/:day/:title/
future: true # Show future-dated posts (if needed)

# Jekyll settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
